### PR TITLE
A few fixes

### LINKED ISSUE #11: Engine fails when a file path contains a colon
The problem is on [this line](https://github.com/jpignata/codeclimate-markdownlint/blob/6d5a36fda651eac99259d3f541115500c53ffc7c/lib/cc/engine/markdownlint.rb#L53):

``` ruby
 match_data = line.match(/(?<path>[^:]*):(?<line_number>\d+): (?<code>MD\d+) (?<description>.*)/)
```

specifically the `[^:]*` pattern, which stipulates that a file path is (translating from regex to English) _anything except a colon_

I think changing this to simply `.*` would work fine.

### LINKED ISSUE #12: When an exception occurs, the engine hangs indefinitely
When I stumbled on #11, it manifested as an engine timeout. After some digging, I realized that the engine is hanging on this line: https://github.com/jpignata/codeclimate-markdownlint/blob/6d5a36fda651eac99259d3f541115500c53ffc7c/lib/cc/engine/markdownlint.rb#L28

``` ruby
STDERR.print err.read
```

It seems like specifically `err.read` is a blocking operation.

If, however, I simply remove that whole line, the exception is still printed to stderr, and the engine doesn't hang.

### PR DESCRIPTION
**Pull request by maxjacobson**
Close #11 
Close #12 

@codeclimate/review 👀

### CODE REVIEW

File: lib/cc/engine/markdownlint.rb [hunk 1]
```diff
@@ -7,33 +7,37 @@ module Engine
...
         @io = io
+        @err_io = err_io
         @contents = {}
       end
 
       def run
         return if include_paths.length == 0
 
-        pid, _, out, err = POSIX::Spawn.popen4("mdl", *mdl_options, *include_paths)
+        command = ["mdl", mdl_options, include_paths].flatten.join(" ")
```
Comment (wfleming) [inline lib/cc/engine/markdownlint.rb]: This is potentially problematic with path names that have spaces in them: you'all end up creating a command string referencing invalid paths. 

`Child.new` can take multiple args, similar to `popen4`. I think you could do `Child.new("mdl", *mdl_options, *include_paths)`.

File: lib/cc/engine/markdownlint.rb [hunk 2]
```diff
@@ -7,33 +7,37 @@ module Engine
...
+        child = POSIX::Spawn::Child.new(command)
```
Comment (wfleming) [inline lib/cc/engine/markdownlint.rb]: This may be pre-existing behavior, but does this engine not error out if the underlying mdl process errors?  That seems undesirable. Should we have an issue filed for that?

File: lib/cc/engine/markdownlint.rb [hunk 3]
```diff
@@ -49,8 +53,10 @@ def mdl_options
         options
       end
 
+      EXPECTED_PATTERN = /(?<path>.*):(?<line_number>\d+): (?<code>MD\d+) (?<description>.*)/
```
Comment (wfleming) [inline lib/cc/engine/markdownlint.rb]: Bikeshedding this name: "expected" doesn't indicate what this text describes. `ISSUE_PATTERN`, or something like that, maybe?

File: lib/cc/engine/markdownlint.rb [hunk 4]
```diff
@@ -7,33 +7,37 @@ module Engine
     class Markdownlint
       CONFIG_FILE = "./.mdlrc".freeze
       EXTENSIONS = %w[.markdown .md].freeze
+      UnexpectedMessageFormat = Class.new(StandardError)
 
-      def initialize(root, engine_config, io)
+      def initialize(root, engine_config, io, err_io = STDERR)
```
Comment (wfleming) [inline lib/cc/engine/markdownlint.rb]: If `io` is a required argument, `err_io` probably should be as well.

File: lib/cc/engine/markdownlint.rb [hunk 5]
```diff
@@ -7,33 +7,36 @@ module Engine
...
         @io = io
+        @err_io = err_io
         @contents = {}
       end
 
       def run
         return if include_paths.length == 0
 
-        pid, _, out, err = POSIX::Spawn.popen4("mdl", *mdl_options, *include_paths)
+        child = POSIX::Spawn::Child.new("mdl", *mdl_options, *include_paths)
```
Comment (maxjacobson) [inline lib/cc/engine/markdownlint.rb:23]: @wfleming following up to collapsed https://github.com/codeclimate/codeclimate-markdownlint/pull/16#discussion_r85044363

> This may be pre-existing behavior, but does this engine not error out if the underlying mdl process errors? That seems undesirable. Should we have an issue filed for that?

Correct. I'm not sure how to define "the underlying process errored out". Possible definitions, and their flaws:
1. `mdl` has a non-zero exit code -- no good, because it exits 1 when it finds issues in markdown files
2. `mdl` prints _anything_ to stderr -- feels wrong, because maybe it just prints some messages to stderr in non-fatal contexts
3. `mdl` prints _something_ to stderr which looks like a ruby stack trace (just thought of this one. Feels weird though)

The assumption I have is that if `mdl` errors out, there _may_ be ill-formatted output printed to stdout, which would lead to us raising our new error. If not, it'll just silently fail and find no issues. Not great.

I think it would be handy if `mdl` exited:
1. `0` for no issues
2. `1` for unhandled runtime error
3. `2` (or something else) for some issues

But that isn't the case, currently.

Any other thoughts on how we can do this? It feels like we should have a good technique here and it will be obvious when I wake up.

Comment (pbrisbin) [reply lib/cc/engine/markdownlint.rb:23]: I think the best answer would be a PR on mivok/markdownlint to add an option to exit zero even if issues are found. I would check around on some other tools, I think some call it `--quiet`, but I'm not a fan of that; maybe `--supress-error`?

**Comment by wfleming** [comment]
Agreed. The other route to go is what we did for ESLint, and actually load up the gem code & run it ourselves rather than forking out to the mdl binary. 

This is previous behavior, though, so we shouldn't worry about it too much right now. We can file an issue to track it.

**Comment by wfleming** [comment]
LGTM

**Comment by maxjacobson** [comment]
agreed, going to merge and capture the above idea for next steps
